"use strict";
(()=> {
const $=id=>document.getElementById(id);
const DB="mivdak-private-v1", STORE="results";
const openDB=()=>new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(STORE))d.createObjectStore(STORE,{keyPath:"id"})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});
async function all(){const d=await openDB();return new Promise((res,rej)=>{const t=d.transaction(STORE,"readonly"),r=t.objectStore(STORE).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);t.oncomplete=()=>d.close()})}
async function put(v){const d=await openDB();return new Promise((res,rej)=>{const t=d.transaction(STORE,"readwrite");t.objectStore(STORE).put(v);t.oncomplete=()=>{d.close();res()};t.onerror=()=>rej(t.error)})}
async function del(id){const d=await openDB();return new Promise((res,rej)=>{const t=d.transaction(STORE,"readwrite");t.objectStore(STORE).delete(id);t.oncomplete=()=>{d.close();res()};t.onerror=()=>rej(t.error)})}
const safe=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const bytes=a=>Array.from(a), encode=s=>new TextEncoder().encode(s),decode=b=>new TextDecoder().decode(b);
async function key(pass,salt){const base=await crypto.subtle.importKey("raw",encode(pass),"PBKDF2",false,["deriveKey"]);return crypto.subtle.deriveKey({name:"PBKDF2",salt,iterations:250000,hash:"SHA-256"},base,{name:"AES-GCM",length:256},false,["encrypt","decrypt"])}
function download(data,name){const u=URL.createObjectURL(new Blob([data],{type:"application/json"}));const a=document.createElement("a");a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),30000)}
const groupKey=r=>r.name.trim().toLocaleLowerCase("he")+"|"+r.unit.trim().toLocaleLowerCase("he");
let currentGroup=null;
async function render(){try{const records=(await all()).sort((a,b)=>b.date.localeCompare(a.date)),groups=new Map();for(const r of records){const k=groupKey(r);if(!groups.has(k))groups.set(k,[]);groups.get(k).push(r)}$("private-list").innerHTML=groups.size?[...groups].map(([k,rs])=>'<article class="card"><h3>'+safe(rs[0].name)+'</h3><p>תוצאה אחרונה: <b dir="ltr">'+safe(rs[0].value)+' '+safe(rs[0].unit)+'</b> · '+safe(rs[0].date)+'</p><p>'+rs.length+' תוצאות שמורות</p><button class="btn secondary" data-history="'+safe(k)+'" aria-label="הצגת היסטוריה וגרף של '+safe(rs[0].name)+'">📈 הצגת היסטוריה וגרף</button></article>').join(""):'<p>אין עדיין תוצאות שמורות במכשיר הזה.</p>'}catch(e){status("לא ניתן לפתוח את האחסון המקומי. בדוק שהדפדפן מאפשר שמירת נתוני אתר.")}}
function numeric(s){const n=Number(String(s).trim().replace(",","."));return Number.isFinite(n)?n:null}
async function showHistory(k){currentGroup=k;const rs=(await all()).filter(r=>groupKey(r)===k).sort((a,b)=>a.date.localeCompare(b.date));if(!rs.length){window.mivdakPrivateOpen();return}const unit=rs[0].unit,valid=rs.map(r=>({r,n:numeric(r.value)})).filter(x=>x.n!==null);let graph='<p>אין די ערכים מספריים להצגת גרף.</p>';if(valid.length>=2){const vals=valid.map(x=>x.n),lo=Math.min(...vals),hi=Math.max(...vals),span=hi-lo||1,w=640,h=270,p=55;const times=valid.map(x=>Date.parse(x.r.date+"T12:00:00")),t0=Math.min(...times),t1=Math.max(...times),timeSpan=t1-t0;const pts=valid.map((x,i)=>({x:timeSpan?p+(times[i]-t0)/timeSpan*(w-2*p):p+i*(w-2*p)/(valid.length-1),y:h-p-(x.n-lo)/span*(h-2*p)}));const first=valid[0].r.date,last=valid[valid.length-1].r.date;graph='<svg viewBox="0 0 '+w+' '+h+'" role="img" aria-label="גרף מגמת תוצאות '+safe(rs[0].name)+'. ערכי הגרף מופיעים גם ברשימה מתחתיו." style="width:100%;max-width:750px;background:#e9f7f3;border-radius:12px"><path d="M'+p+' '+p+' V'+(h-p)+' H'+(w-p)+'" fill="none" stroke="#55716c" stroke-width="2"/><polyline fill="none" stroke="#087669" stroke-width="3" points="'+pts.map(q=>q.x+','+q.y).join(" ")+'"/>'+pts.map((q,i)=>'<circle cx="'+q.x+'" cy="'+q.y+'" r="6" fill="#087669"><title>'+safe(valid[i].r.date+': '+valid[i].r.value+' '+unit)+'</title></circle>').join("")+'<text x="'+(p-5)+'" y="'+(p-12)+'" fill="#075e57" font-size="16">'+safe(String(hi))+'</text><text x="'+(p-5)+'" y="'+(h-p+20)+'" fill="#075e57" font-size="16">'+safe(String(lo))+'</text><text x="'+p+'" y="'+(h-9)+'" fill="#075e57" font-size="16" direction="ltr">'+safe(first)+'</text><text x="'+(w-p)+'" y="'+(h-9)+'" text-anchor="end" fill="#075e57" font-size="16" direction="ltr">'+safe(last)+'</text></svg><p>המרחק האופקי בין הנקודות משקף את הזמן שחלף בין הבדיקות. כאשר כל הבדיקות באותו תאריך, הנקודות מוצגות במרווח שווה. ערכים ותאריכים מלאים מופיעים גם ברשימה להלן.</p><p>אין להסיק אבחנה מהגרף. טווחי ייחוס עשויים להשתנות בין דוחות ומעבדות.</p>'}document.querySelectorAll(".view").forEach(v=>v.hidden=v.id!=="history-page");$("history-content").innerHTML='<h2>'+safe(rs[0].name)+'</h2><p>יחידות: '+safe(unit||"לא צוינו")+'</p>'+graph+'<h3>כל התוצאות</h3>'+rs.slice().reverse().map(r=>'<article class="card"><p><strong>'+safe(r.date)+'</strong> · <b dir="ltr">'+safe(r.value)+' '+safe(r.unit)+'</b></p><p>טווח בדוח: '+safe(r.range||"לא הוזן")+'</p><button class="btn secondary" data-delete="'+safe(r.id)+'">מחיקת תוצאה</button></article>').join("");window.scrollTo(0,0)}
function status(s){$("private-status").textContent=s}
window.mivdakPrivateOpen=async()=>{document.querySelectorAll(".view").forEach(v=>v.hidden=v.id!=="private-page");window.scrollTo(0,0);await render()};
$("private-form").addEventListener("submit",async e=>{e.preventDefault();const f=e.target;const r={id:crypto.randomUUID(),date:f.elements.date.value,name:f.elements.testname.value.trim(),value:f.elements.result.value.trim(),unit:f.elements.unit.value.trim(),range:f.elements.range.value.trim()};if(!r.date||!r.name||!r.value){status("יש למלא תאריך, שם בדיקה ותוצאה.");return}try{await put(r);f.reset();status("התוצאה נשמרה במכשיר זה בלבד.");await render()}catch(err){status("השמירה נכשלה. בדוק שיש מקום פנוי ואחסון מותר.")}});
$("private-list").addEventListener("click",async e=>{const h=e.target.closest("[data-history]");if(h){await showHistory(h.dataset.history);return}const b=e.target.closest("[data-delete]");if(!b||!confirm("למחוק את התוצאה מהמכשיר?"))return;await del(b.dataset.delete);await render()});
$("history-content").addEventListener("click",async e=>{const b=e.target.closest("[data-delete]");if(!b||!confirm("למחוק את התוצאה מהמכשיר?"))return;await del(b.dataset.delete);await showHistory(currentGroup)});
$("history-back").addEventListener("click",()=>window.mivdakPrivateOpen());
$("backup-btn").addEventListener("click",async()=>{try{if(!crypto.subtle)throw Error("crypto");const pass=prompt("בחר סיסמה חזקה לגיבוי המוצפן (לפחות 12 תווים). שמור אותה: בלעדיה לא ניתן לשחזר.");if(pass===null)return;if(pass.length<12){status("יש לבחור סיסמה בת 12 תווים לפחות.");return}const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12));const encrypted=await crypto.subtle.encrypt({name:"AES-GCM",iv},await key(pass,salt),encode(JSON.stringify(await all())));download(JSON.stringify({format:"mivdak-backup-v1",salt:bytes(salt),iv:bytes(iv),data:bytes(new Uint8Array(encrypted))}),"mivdak-backup-"+new Date().toISOString().slice(0,10)+".json");status("קובץ גיבוי מוצפן נוצר. שמור אותו ואת הסיסמה בנפרד.")}catch(e){status("יצירת הגיבוי נכשלה.")}});
$("restore-file").addEventListener("change",async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>5e6)throw Error("size");const obj=JSON.parse(await f.text());if(obj.format!=="mivdak-backup-v1"||![obj.salt,obj.iv,obj.data].every(Array.isArray))throw Error("format");const pass=prompt("הכנס את סיסמת הגיבוי המוצפן:");if(pass===null)return;const decrypted=await crypto.subtle.decrypt({name:"AES-GCM",iv:new Uint8Array(obj.iv)},await key(pass,new Uint8Array(obj.salt)),new Uint8Array(obj.data));const records=JSON.parse(decode(decrypted));if(!Array.isArray(records)||records.length>10000||!records.every(r=>typeof r.id==="string"&&typeof r.date==="string"&&typeof r.name==="string"&&typeof r.value==="string"))throw Error("data");if(!confirm("לשחזר "+records.length+" תוצאות? תוצאות עם מזהה זהה יוחלפו."))return;for(const r of records)await put({id:r.id,date:r.date,name:r.name,value:r.value,unit:String(r.unit||""),range:String(r.range||"")});status("השחזור הסתיים.");await render()}catch(err){status("השחזור נכשל: קובץ לא תקין או סיסמה שגויה.")}finally{e.target.value=""}});
$("pdf-file").addEventListener("change",e=>{const f=e.target.files[0];status(f?"הקובץ לא נשלח לשום שרת. חילוץ אוטומטי מ־PDF עדיין אינו פעיל; ניתן להזין את הנתונים ידנית.":"");e.target.value=""});
})();