"use strict";
(()=> {
const $=id=>document.getElementById(id);
const DB="mivdak-private-v1", STORE="results";
const openDB=()=>new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(STORE))d.createObjectStore(STORE,{keyPath:"id"})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});
async function all(){const d=await openDB();return new Promise((res,rej)=>{const t=d.transaction(STORE,"readonly"),r=t.objectStore(STORE).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);t.oncomplete=()=>d.close()})}
async function put(v){const d=await openDB();return new Promise((res,rej)=>{const t=d.transaction(STORE,"readwrite");t.objectStore(STORE).put(v);t.oncomplete=()=>{d.close();res()};t.onerror=()=>rej(t.error)})}
async function del(id){const d=await openDB();return new Promise((res,rej)=>{const t=d.transaction(STORE,"readwrite");t.objectStore(STORE).delete(id);t.oncomplete=()=>{d.close();res()};t.onerror=()=>rej(t.error)})}
const safe=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const bytes=a=>Array.from(a), encode=s=>new TextEncoder().encode(s),decode=b=>new TextDecoder().decode(b);
async function key(pass,salt){const base=await crypto.subtle.importKey("raw",encode(pass),"PBKDF2",false,["deriveKey"]);return crypto.subtle.deriveKey({name:"PBKDF2",salt,iterations:250000,hash:"SHA-256"},base,{name:"AES-GCM",length:256},false,["encrypt","decrypt"])}
function download(data,name){const u=URL.createObjectURL(new Blob([data],{type:"application/json"}));const a=document.createElement("a");a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),30000)}
const groupKey=r=>r.name.trim().toLocaleLowerCase("he")+"|"+r.unit.trim().toLocaleLowerCase("he");
let currentGroup=null;
async function render(){try{const records=(await all()).sort((a,b)=>b.date.localeCompare(a.date)),groups=new Map();for(const r of records){const k=groupKey(r);if(!groups.has(k))groups.set(k,[]);groups.get(k).push(r)}$("private-list").innerHTML=groups.size?[...groups].map(([k,rs])=>'<article class="card"><h3>'+safe(rs[0].name)+'</h3><p>תוצאה אחרונה: <b dir="ltr">'+safe(rs[0].value)+' '+safe(rs[0].unit)+'</b> · '+safe(rs[0].date)+'</p><p>'+rs.length+' תוצאות שמורות</p><button class="btn secondary" data-history="'+safe(k)+'" aria-label="הצגת היסטוריה וגרף של '+safe(rs[0].name)+'">📈 הצגת היסטוריה וגרף</button></article>').join(""):'<p>אין עדיין תוצאות שמורות במכשיר הזה.</p>'}catch(e){status("לא ניתן לפתוח את האחסון המקומי. בדוק שהדפדפן מאפשר שמירת נתוני אתר.")}}
function numeric(s){const n=Number(String(s).trim().replace(",","."));return Number.isFinite(n)?n:null}
async function showHistory(k){currentGroup=k;const rs=(await all()).filter(r=>groupKey(r)===k).sort((a,b)=>a.date.localeCompare(b.date));if(!rs.length){window.mivdakPrivateOpen();return}const unit=rs[0].unit,valid=rs.map(r=>({r,n:numeric(r.value)})).filter(x=>x.n!==null);let graph='<p>אין די ערכים מספריים להצגת גרף.</p>';if(valid.length>=2){const vals=valid.map(x=>x.n),lo=Math.min(...vals),hi=Math.max(...vals),span=hi-lo||1,w=640,h=270,p=55;const times=valid.map(x=>Date.parse(x.r.date+"T12:00:00")),t0=Math.min(...times),t1=Math.max(...times),timeSpan=t1-t0;const pts=valid.map((x,i)=>({x:timeSpan?p+(times[i]-t0)/timeSpan*(w-2*p):p+i*(w-2*p)/(valid.length-1),y:h-p-(x.n-lo)/span*(h-2*p)}));const first=valid[0].r.date,last=valid[valid.length-1].r.date;graph='<svg viewBox="0 0 '+w+' '+h+'" role="img" aria-label="גרף מגמת תוצאות '+safe(rs[0].name)+'. ערכי הגרף מופיעים גם ברשימה מתחתיו." style="width:100%;max-width:750px;background:#e9f7f3;border-radius:12px"><path d="M'+p+' '+p+' V'+(h-p)+' H'+(w-p)+'" fill="none" stroke="#55716c" stroke-width="2"/><polyline fill="none" stroke="#087669" stroke-width="3" points="'+pts.map(q=>q.x+','+q.y).join(" ")+'"/>'+pts.map((q,i)=>'<circle cx="'+q.x+'" cy="'+q.y+'" r="6" fill="#087669"><title>'+safe(valid[i].r.date+': '+valid[i].r.value+' '+unit)+'</title></circle>').join("")+'<text x="'+(p-5)+'" y="'+(p-12)+'" fill="#075e57" font-size="16">'+safe(String(hi))+'</text><text x="'+(p-5)+'" y="'+(h-p+20)+'" fill="#075e57" font-size="16">'+safe(String(lo))+'</text><text x="'+p+'" y="'+(h-9)+'" fill="#075e57" font-size="16" direction="ltr">'+safe(first)+'</text><text x="'+(w-p)+'" y="'+(h-9)+'" text-anchor="end" fill="#075e57" font-size="16" direction="ltr">'+safe(last)+'</text></svg><p>המרחק האופקי בין הנקודות משקף את הזמן שחלף בין הבדיקות. כאשר כל הבדיקות באותו תאריך, הנקודות מוצגות במרווח שווה. ערכים ותאריכים מלאים מופיעים גם ברשימה להלן.</p><p>אין להסיק אבחנה מהגרף. טווחי ייחוס עשויים להשתנות בין דוחות ומעבדות.</p>'}document.querySelectorAll(".view").forEach(v=>v.hidden=v.id!=="history-page");$("history-content").innerHTML='<h2>'+safe(rs[0].name)+'</h2><p>יחידות: '+safe(unit||"לא צוינו")+'</p>'+graph+'<h3>כל התוצאות</h3>'+rs.slice().reverse().map(r=>'<article class="card"><p><strong>'+safe(r.date)+'</strong> · <b dir="ltr">'+safe(r.value)+' '+safe(r.unit)+'</b></p><p>טווח בדוח: '+safe(r.range||"לא הוזן")+'</p><button class="btn secondary" data-delete="'+safe(r.id)+'">מחיקת תוצאה</button></article>').join("");window.scrollTo(0,0)}
function status(s){$("private-status").textContent=s}
window.mivdakPrivateOpen=async()=>{document.querySelectorAll(".view").forEach(v=>v.hidden=v.id!=="private-page");window.scrollTo(0,0);await render()};
$("private-form").addEventListener("submit",async e=>{e.preventDefault();const f=e.target;const r={id:crypto.randomUUID(),date:f.elements.date.value,name:f.elements.testname.value.trim(),value:f.elements.result.value.trim(),unit:f.elements.unit.value.trim(),range:f.elements.range.value.trim()};if(!r.date||!r.name||!r.value){status("יש למלא תאריך, שם בדיקה ותוצאה.");return}try{await put(r);f.reset();status("התוצאה נשמרה במכשיר זה בלבד.");await render()}catch(err){status("השמירה נכשלה. בדוק שיש מקום פנוי ואחסון מותר.")}});
$("private-list").addEventListener("click",async e=>{const h=e.target.closest("[data-history]");if(h){await showHistory(h.dataset.history);return}const b=e.target.closest("[data-delete]");if(!b||!confirm("למחוק את התוצאה מהמכשיר?"))return;await del(b.dataset.delete);await render()});
$("history-content").addEventListener("click",async e=>{const b=e.target.closest("[data-delete]");if(!b||!confirm("למחוק את התוצאה מהמכשיר?"))return;await del(b.dataset.delete);await showHistory(currentGroup)});
$("history-back").addEventListener("click",()=>window.mivdakPrivateOpen());
$("backup-btn").addEventListener("click",async()=>{try{if(!crypto.subtle)throw Error("crypto");const pass=prompt("בחר סיסמה חזקה לגיבוי המוצפן (לפחות 12 תווים). שמור אותה: בלעדיה לא ניתן לשחזר.");if(pass===null)return;if(pass.length<12){status("יש לבחור סיסמה בת 12 תווים לפחות.");return}const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12));const encrypted=await crypto.subtle.encrypt({name:"AES-GCM",iv},await key(pass,salt),encode(JSON.stringify(await all())));download(JSON.stringify({format:"mivdak-backup-v1",salt:bytes(salt),iv:bytes(iv),data:bytes(new Uint8Array(encrypted))}),"mivdak-backup-"+new Date().toISOString().slice(0,10)+".json");status("קובץ גיבוי מוצפן נוצר. שמור אותו ואת הסיסמה בנפרד.")}catch(e){status("יצירת הגיבוי נכשלה.")}});
$("restore-file").addEventListener("change",async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>5e6)throw Error("size");const obj=JSON.parse(await f.text());if(obj.format!=="mivdak-backup-v1"||![obj.salt,obj.iv,obj.data].every(Array.isArray))throw Error("format");const pass=prompt("הכנס את סיסמת הגיבוי המוצפן:");if(pass===null)return;const decrypted=await crypto.subtle.decrypt({name:"AES-GCM",iv:new Uint8Array(obj.iv)},await key(pass,new Uint8Array(obj.salt)),new Uint8Array(obj.data));const records=JSON.parse(decode(decrypted));if(!Array.isArray(records)||records.length>10000||!records.every(r=>typeof r.id==="string"&&typeof r.date==="string"&&typeof r.name==="string"&&typeof r.value==="string"))throw Error("data");if(!confirm("לשחזר "+records.length+" תוצאות? תוצאות עם מזהה זהה יוחלפו."))return;for(const r of records)await put({id:r.id,date:r.date,name:r.name,value:r.value,unit:String(r.unit||""),range:String(r.range||"")});status("השחזור הסתיים.");await render()}catch(err){status("השחזור נכשל: קובץ לא תקין או סיסמה שגויה.")}finally{e.target.value=""}});
let pdfCandidates=[];
function isoDate(text){const m=String(text).match(/(\d{1,2})[.\/-](\d{1,2})[.\/-](20\d{2})/);return m?m[3]+"-"+m[2].padStart(2,"0")+"-"+m[1].padStart(2,"0"):new Date().toISOString().slice(0,10)}
const LAB_TESTS=["glucose","urea","creatinine","egfr","potassium","sodium","calcium","wbc","leucocytes","leukocytes","rbc","red blood cells","hemoglobin","haemoglobin","hematocrit","haematocrit","mcv","mch","mchc","rdw","platelets","mpv","neutrophils","lymphocytes","monocytes","eosinophils","basophils"];
function parseLabLines(lines,full){const date=isoDate(full),out=[],seen=new Set();for(let i=0;i<lines.length;i++){const line=String(lines[i]).replace(/\s+/g," ").trim(),low=line.toLowerCase();const test=LAB_TESTS.find(t=>low.includes(t));if(!test)continue;const windowText=[lines[i-1]||"",line,lines[i+1]||""].join(" ").replace(/\s+/g," ");const nums=[...windowText.matchAll(/(?:^|\s)([<>]?-?\d+(?:[.,]\d+)?)(?=\s|$)/g)].map(x=>x[1]);if(!nums.length)continue;let value=nums.find(n=>{const v=Number(n.replace(",","."));return Number.isFinite(v)&&v<10000});if(!value)continue;const unitMatch=windowText.match(/(?:mg\/dl|mmol\/l|g\/dl|g\/l|fl|pg(?:\/cell)?|%|10\^?[369]\/?(?:micl|ul|l)|10\*?[369]\/?(?:micl|ul|l)|ml\/min\/1\.73m²?)/i);const rangeMatch=windowText.match(/(-?\d+(?:[.,]\d+)?)\s*(?:[-–]|\.{2,})\s*(-?\d+(?:[.,]\d+)?)/);let name=line.replace(/[<>]?-?\d+(?:[.,]\d+)?/g," ").replace(/\s+/g," ").trim();const canonical={"leucocytes":"WBC-Leucocytes","leukocytes":"WBC-Leucocytes","red blood cells":"RBC-Red Blood Cells","haemoglobin":"Hemoglobin"};name=canonical[test]||name;if(name.length>80||name.length<2)name=test;const k=test+"|"+value;if(seen.has(k))continue;seen.add(k);out.push({date,name,value,unit:unitMatch?unitMatch[0]:"",range:rangeMatch?rangeMatch[1]+"–"+rangeMatch[2]:""})}return out.slice(0,100)}
function previewPDF(rows){pdfCandidates=rows;$("pdf-preview").hidden=true;$("pdf-open-results").hidden=!rows.length;$("pdf-open-results").textContent=rows.length?"📋 הצגת "+rows.length+" התוצאות שזוהו":"📋 הצגת התוצאות שזוהו";$("pdf-count").textContent=rows.length?"נמצאו "+rows.length+" תוצאות אפשריות":"";$("pdf-rows").innerHTML=rows.length?rows.map((r,i)=>'<article class="pdf-card"><div class="pdf-card-main"><input class="pdf-check" type="checkbox" checked data-pick="'+i+'" aria-label="שמירת '+safe(r.name)+'"><div><div class="pdf-card-name">'+safe(r.name)+'</div><div class="pdf-meta">'+safe(r.date)+(r.range?' · טווח '+safe(r.range):'')+'</div></div><div><div class="pdf-card-value">'+safe(r.value)+' '+safe(r.unit)+'</div><button class="pdf-edit-toggle" type="button" data-edit="'+i+'">עריכה</button></div></div><div class="pdf-edit" data-editor="'+i+'" hidden><div class="pdf-fields"><label>תאריך<input data-pdf="'+i+'" data-field="date" type="date" value="'+safe(r.date)+'"></label><label>שם הבדיקה<input data-pdf="'+i+'" data-field="name" value="'+safe(r.name)+'"></label><label>תוצאה<input data-pdf="'+i+'" data-field="value" value="'+safe(r.value)+'"></label><label>יחידות<input data-pdf="'+i+'" data-field="unit" value="'+safe(r.unit)+'"></label><label>טווח בדוח<input data-pdf="'+i+'" data-field="range" value="'+safe(r.range)+'"></label></div></div></article>').join(""):'<p>לא זוהו תוצאות באופן אוטומטי.</p>';$("pdf-save").hidden=!rows.length}
$("pdf-open-results").addEventListener("click",()=>{if(pdfCandidates.length){$("pdf-preview").hidden=false;document.body.style.overflow="hidden"}});
$("pdf-rows").addEventListener("click",e=>{const b=e.target.closest("[data-edit]");if(!b)return;const box=$("pdf-rows").querySelector('[data-editor="'+b.dataset.edit+'"]');box.hidden=!box.hidden;b.textContent=box.hidden?"עריכה":"סגירת עריכה"});
$("pdf-rows").addEventListener("input",e=>{const el=e.target.closest("[data-pdf]");if(el)pdfCandidates[Number(el.dataset.pdf)][el.dataset.field]=el.value});
$("pdf-close").addEventListener("click",()=>$("pdf-cancel").click());
$("pdf-preview").addEventListener("click",e=>{if(e.target===$("pdf-preview"))$("pdf-cancel").click()});
$("pdf-cancel").addEventListener("click",()=>{$("pdf-preview").hidden=true;$("pdf-rows").innerHTML="";pdfCandidates=[];$("pdf-open-results").hidden=true;document.body.style.overflow=""});
$("pdf-save").addEventListener("click",async()=>{const picks=[...$("pdf-rows").querySelectorAll("[data-pick]")].filter(x=>x.checked).map(x=>Number(x.dataset.pick));if(!picks.length){status("לא נבחרו תוצאות לשמירה.");return}for(const i of picks){const r=pdfCandidates[i];if(!r.name.trim()||!r.value.trim())continue;await put({id:crypto.randomUUID(),date:r.date||new Date().toISOString().slice(0,10),name:r.name.trim(),value:r.value.trim(),unit:r.unit.trim(),range:r.range.trim()})}$("pdf-preview").hidden=true;$("pdf-rows").innerHTML="";pdfCandidates=[];$("pdf-open-results").hidden=true;document.body.style.overflow="";status("התוצאות שאישרת נשמרו במכשיר.");await render()});
async function loadOCR(){if(window.Tesseract)return window.Tesseract;await new Promise((ok,bad)=>{const x=document.createElement("script");x.src="/vendor/tesseract/tesseract.min.js";x.onload=ok;x.onerror=bad;document.head.appendChild(x)});return window.Tesseract}
async function scanPDF(doc){status("המסמך הוא סריקה — מפעיל זיהוי מקומי…");const T=await Promise.race([loadOCR(),new Promise((_,rej)=>setTimeout(()=>rej(Error("ocr-timeout")),15000))]),worker=await Promise.race([T.createWorker("eng",1,{workerPath:"/vendor/tesseract/worker.min.js",corePath:"/vendor/tesseract/core/tesseract-core-simd-lstm.wasm.js",langPath:"/vendor/tesseract/lang",logger:m=>{if(m.status==="recognizing text")status("מזהה טקסט בסריקה… "+Math.round((m.progress||0)*100)+"%")}}),new Promise((_,rej)=>setTimeout(()=>rej(Error("ocr-timeout")),30000))]),lines=[],full=[];try{for(let n=1;n<=doc.numPages;n++){status("מזהה עמוד "+n+" מתוך "+doc.numPages+"…");const page=await doc.getPage(n),vp=page.getViewport({scale:2}),c=document.createElement("canvas");c.width=Math.ceil(vp.width);c.height=Math.ceil(vp.height);await page.render({canvasContext:c.getContext("2d",{willReadFrequently:true}),viewport:vp}).promise;const z=await worker.recognize(c),t=z.data.text||"";full.push(t);lines.push(...t.split(/\r?\n/))}}finally{await worker.terminate()}return {lines,full:full.join(" ")}}
$("pdf-file").addEventListener("change",async e=>{const f=e.target.files[0];if(!f)return;try{if(f.type!=="application/pdf"&&!/\.pdf$/i.test(f.name))throw Error("type");if(f.size>20e6)throw Error("size");status("קורא את ה־PDF במכשיר…");const pdfjs=await import("/vendor/pdfjs/pdf.min.mjs");pdfjs.GlobalWorkerOptions.workerSrc="/vendor/pdfjs/pdf.worker.min.mjs";const doc=await pdfjs.getDocument({data:new Uint8Array(await f.arrayBuffer())}).promise;const lines=[],allText=[];for(let n=1;n<=doc.numPages;n++){const page=await doc.getPage(n),tc=await page.getTextContent(),groups=new Map();for(const item of tc.items){if(!item.str)continue;allText.push(item.str);const y=Math.round(item.transform?.[5]||0);if(!groups.has(y))groups.set(y,[]);groups.get(y).push(item)}for(const items of groups.values()){items.sort((a,b)=>(a.transform?.[4]||0)-(b.transform?.[4]||0));lines.push(items.map(x=>x.str).join(" "))}}let usedOCR=false;if(allText.join("").replace(/\\s/g,"").length<40){usedOCR=true;const o=await scanPDF(doc);lines.splice(0,lines.length,...o.lines);allText.splice(0,allText.length,o.full)}const rows=parseLabLines(lines,allText.join(" "));previewPDF(rows);status(rows.length?(usedOCR?"הסריקה זוהתה מקומית. נמצאו ":"נמצאו ")+rows.length+" שורות אפשריות. בדוק כל נתון מול ה־PDF לפני השמירה.":usedOCR?"המסמך זוהה כסריקה, אך לא חולצו תוצאות בבטחה. לא נשמר דבר.":"לא זוהו תוצאות אוטומטית. לא נשמר דבר.")}catch(err){status(err.message==="size"?"הקובץ גדול מדי לייבוא (מעל 20MB).":err.message==="ocr-timeout"?"מנוע הזיהוי לא הצליח להיטען בזמן. נסה שוב לאחר בדיקת החיבור או הזן ידנית.":"לא הצלחתי לקרוא את ה־PDF. אפשר לנסות PDF אחר או להזין ידנית.")}finally{e.target.value=""}});
})();