"use strict";
(()=> {
const $=id=>document.getElementById(id);
const DB="mivdak-private-v1", STORE="results";
const openDB=()=>new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(STORE))d.createObjectStore(STORE,{keyPath:"id"})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});
async function all(){const d=await openDB();return new Promise((res,rej)=>{const t=d.transaction(STORE,"readonly"),r=t.objectStore(STORE).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);t.oncomplete=()=>d.close()})}
async function put(v){const d=await openDB();return new Promise((res,rej)=>{const t=d.transaction(STORE,"readwrite");t.objectStore(STORE).put(v);t.oncomplete=()=>{d.close();res()};t.onerror=()=>rej(t.error)})}
async function del(id){const d=await openDB();return new Promise((res,rej)=>{const t=d.transaction(STORE,"readwrite");t.objectStore(STORE).delete(id);t.oncomplete=()=>{d.close();res()};t.onerror=()=>rej(t.error)})}
const safe=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const bytes=a=>Array.from(a), encode=s=>new TextEncoder().encode(s),decode=b=>new TextDecoder().decode(b);
async function key(pass,salt){const base=await crypto.subtle.importKey("raw",encode(pass),"PBKDF2",false,["deriveKey"]);return crypto.subtle.deriveKey({name:"PBKDF2",salt,iterations:250000,hash:"SHA-256"},base,{name:"AES-GCM",length:256},false,["encrypt","decrypt"])}
function download(data,name){const u=URL.createObjectURL(new Blob([data],{type:"application/json"}));const a=document.createElement("a");a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),30000)}
async function render(){try{const records=(await all()).sort((a,b)=>b.date.localeCompare(a.date));$("private-list").innerHTML=records.length?records.map(r=>'<article class="card"><h3>'+safe(r.name)+'</h3><p>'+safe(r.date)+' · <b dir="ltr">'+safe(r.value)+' '+safe(r.unit)+'</b></p><p>טווח בדוח: '+safe(r.range||"לא הוזן")+'</p><button class="btn secondary" data-delete="'+safe(r.id)+'">מחיקת תוצאה</button></article>').join(""):'<p>אין עדיין תוצאות שמורות במכשיר הזה.</p>'}catch(e){status("לא ניתן לפתוח את האחסון המקומי. בדוק שהדפדפן מאפשר שמירת נתוני אתר.")}}
function status(s){$("private-status").textContent=s}
window.mivdakPrivateOpen=async()=>{document.querySelectorAll(".view").forEach(v=>v.hidden=v.id!=="private-page");window.scrollTo(0,0);await render()};
$("private-form").addEventListener("submit",async e=>{e.preventDefault();const f=e.target;const r={id:crypto.randomUUID(),date:f.elements.date.value,name:f.elements.testname.value.trim(),value:f.elements.result.value.trim(),unit:f.elements.unit.value.trim(),range:f.elements.range.value.trim()};if(!r.date||!r.name||!r.value){status("יש למלא תאריך, שם בדיקה ותוצאה.");return}try{await put(r);f.reset();status("התוצאה נשמרה במכשיר זה בלבד.");await render()}catch(err){status("השמירה נכשלה. בדוק שיש מקום פנוי ואחסון מותר.")}});
$("private-list").addEventListener("click",async e=>{const b=e.target.closest("[data-delete]");if(!b||!confirm("למחוק את התוצאה מהמכשיר?"))return;await del(b.dataset.delete);await render()});
$("backup-btn").addEventListener("click",async()=>{try{if(!crypto.subtle)throw Error("crypto");const pass=prompt("בחר סיסמה חזקה לגיבוי המוצפן (לפחות 12 תווים). שמור אותה: בלעדיה לא ניתן לשחזר.");if(pass===null)return;if(pass.length<12){status("יש לבחור סיסמה בת 12 תווים לפחות.");return}const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12));const encrypted=await crypto.subtle.encrypt({name:"AES-GCM",iv},await key(pass,salt),encode(JSON.stringify(await all())));download(JSON.stringify({format:"mivdak-backup-v1",salt:bytes(salt),iv:bytes(iv),data:bytes(new Uint8Array(encrypted))}),"mivdak-backup-"+new Date().toISOString().slice(0,10)+".json");status("קובץ גיבוי מוצפן נוצר. שמור אותו ואת הסיסמה בנפרד.")}catch(e){status("יצירת הגיבוי נכשלה.")}});
$("restore-file").addEventListener("change",async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>5e6)throw Error("size");const obj=JSON.parse(await f.text());if(obj.format!=="mivdak-backup-v1"||![obj.salt,obj.iv,obj.data].every(Array.isArray))throw Error("format");const pass=prompt("הכנס את סיסמת הגיבוי המוצפן:");if(pass===null)return;const decrypted=await crypto.subtle.decrypt({name:"AES-GCM",iv:new Uint8Array(obj.iv)},await key(pass,new Uint8Array(obj.salt)),new Uint8Array(obj.data));const records=JSON.parse(decode(decrypted));if(!Array.isArray(records)||records.length>10000||!records.every(r=>typeof r.id==="string"&&typeof r.date==="string"&&typeof r.name==="string"&&typeof r.value==="string"))throw Error("data");if(!confirm("לשחזר "+records.length+" תוצאות? תוצאות עם מזהה זהה יוחלפו."))return;for(const r of records)await put({id:r.id,date:r.date,name:r.name,value:r.value,unit:String(r.unit||""),range:String(r.range||"")});status("השחזור הסתיים.");await render()}catch(err){status("השחזור נכשל: קובץ לא תקין או סיסמה שגויה.")}finally{e.target.value=""}});
$("pdf-file").addEventListener("change",e=>{const f=e.target.files[0];status(f?"הקובץ לא נשלח לשום שרת. חילוץ אוטומטי מ־PDF עדיין אינו פעיל; ניתן להזין את הנתונים ידנית.":"");e.target.value=""});
})();